### ISSUE TITLE
Compile errors of bool Melopero_RV3028::isPM() and bool Melopero_RV3028::isEEPROMBusy() in ESP32 Arduino environment.

### ISSUE THREAD

**Issue by HAO156** [melopero/Melopero_RV-3028_Arduino_Library#1]
Thanks for writing the wonderful open source code。
I use ESP32 + Arduino +Melopero_RV3028, and it appears during the compilation process: 
`C:\Users\Melopero_RV3028.cpp: In member function'bool Melopero_RV3028::isPM()':
C:\Users\Melopero_RV3028.cpp:129:53: error: suggest parentheses around comparison in operand of'&' [-Werror=parentheses]
      return readFromRegister(HOURS_REGISTER_ADDRESS) & PM_FLAG> 0;
                                                      ^
C:\Users\Melopero_RV3028.cpp: In member function'bool Melopero_RV3028::isEEPROMBusy()':
C:\Users\Melopero_RV3028\src\Melopero_RV3028.cpp:276:54: error: suggest parentheses around comparison in operand of'&' [-Werror=parentheses]
      return readFromRegister(STATUS_REGISTER_ADDRESS) & 0x80> 0;`

The brackets need to be added. It can be compiled normally after changing to the following.

`bool Melopero_RV3028::isPM(){
    return (readFromRegister(HOURS_REGISTER_ADDRESS) & PM_FLAG) > 0;
}`

`bool Melopero_RV3028::isEEPROMBusy(){
    return (readFromRegister(STATUS_REGISTER_ADDRESS) & 0x80) > 0;
}`

Hope you can fix it.

Best wishes, thank you！

**Comment by leoli51** [comment]
Thank you very much for providing a fix. Your pull request has been accepted and merged. 
Happy coding!
