### ISSUE TITLE
isEEPROMBusy() cannot work.

### ISSUE THREAD

**Issue by BlueTailCat** [melopero/Melopero_RV-3028_Arduino_Library#3]
bool Melopero_RV3028::isEEPROMBusy(){
    return readFromRegister(STATUS_REGISTER_ADDRESS) & 0x80 > 0;
}
This function need a brackets，Otherwise it won't work.

```
bool Melopero_RV3028::isEEPROMBusy(){
    return (readFromRegister(STATUS_REGISTER_ADDRESS) & 0x80) > 0;
}
```

**Comment by leoli51** [comment]
Hi I accepted @HAO156 's pull request and now everything should be working. Thank you very much for your feedback. 
Best regards.

**Comment by BlueTailCat** [comment]
OK, got it
